// AUTOGENERATED TESTS
//   (do not modify)

// RUN with 'jest'


const { testData, testParsing, testParsingDPP } = require('../testDefinitions')


// address
test("address_#1", function (done) {
    var td = testData["address"];
    testParsing(td.uris[0], td.expected, done);
});

// bip21sv
test("bip21sv_#1", function (done) {
    var td = testData["bip21sv"];
    testParsing(td.uris[0], td.expected, done);
});
test("bip21sv_#2", function (done) {
    var td = testData["bip21sv"];
    testParsing(td.uris[1], td.expected, done);
});
test("bip21sv_#3", function (done) {
    var td = testData["bip21sv"];
    testParsing(td.uris[2], td.expected, done);
});

// bip21
test("bip21_#1", function (done) {
    var td = testData["bip21"];
    testParsing(td.uris[0], td.expected, done);
});
test("bip21_#2", function (done) {
    var td = testData["bip21"];
    testParsing(td.uris[1], td.expected, done);
});

// bip21-noParams
test("bip21-noParams_#1", function (done) {
    var td = testData["bip21-noParams"];
    testParsing(td.uris[0], td.expected, done);
});

// bip275-bip282
test("bip275-bip282_#1", function (done) {
    var td = testData["bip275-bip282"];
    testParsing(td.uris[0], td.expected, done);
});
test("bip275-bip282_#2", function (done) {
    var td = testData["bip275-bip282"];
    testParsing(td.uris[1], td.expected, done);
});

// bip275
test("bip275_#1", function (done) {
    var td = testData["bip275"];
    testParsing(td.uris[0], td.expected, done);
});
test("bip275_#2", function (done) {
    var td = testData["bip275"];
    testParsing(td.uris[1], td.expected, done);
});

// bip272strict
test("bip272strict_#1", function (done) {
    var td = testData["bip272strict"];
    testParsing(td.uris[0], td.expected, done);
});
test("bip272strict_#2", function (done) {
    var td = testData["bip272strict"];
    testParsing(td.uris[1], td.expected, done);
});

// bip272
test("bip272_#1", function (done) {
    var td = testData["bip272"];
    testParsing(td.uris[0], td.expected, done);
});
test("bip272_#2", function (done) {
    var td = testData["bip272"];
    testParsing(td.uris[1], td.expected, done);
});

// bip272-noSvParam
test("bip272-noSvParam_#1", function (done) {
    var td = testData["bip272-noSvParam"];
    testParsing(td.uris[0], td.expected, done);
});
test("bip272-noSvParam_#2", function (done) {
    var td = testData["bip272-noSvParam"];
    testParsing(td.uris[1], td.expected, done);
});

// bip272-noSvParam-dpp
test("bip272-noSvParam-dpp_#1", function (done) {
    var td = testData["bip272-noSvParam-dpp"];
    testParsingDPP(td.uris[0], td.expected, done);
});

// paymail
test("paymail_#1", function (done) {
    var td = testData["paymail"];
    testParsing(td.uris[0], td.expected, done);
});

// paymail-P2P-handcash
test("paymail-P2P-handcash_#1", function (done) {
    var td = testData["paymail-P2P-handcash"];
    testParsing(td.uris[0], td.expected, done);
});

// paymail-P2P-moneybutton
test("paymail-P2P-moneybutton_#1", function (done) {
    var td = testData["paymail-P2P-moneybutton"];
    testParsing(td.uris[0], td.expected, done);
});

// paymail-simplycash
test("paymail-simplycash_#1", function (done) {
    var td = testData["paymail-simplycash"];
    testParsing(td.uris[0], td.expected, done);
});

// paymail-noParams
test("paymail-noParams_#1", function (done) {
    var td = testData["paymail-noParams"];
    testParsing(td.uris[0], td.expected, done);
});
test("paymail-noParams_#2", function (done) {
    var td = testData["paymail-noParams"];
    testParsing(td.uris[1], td.expected, done);
});

// paymail-noScheme
test("paymail-noScheme_#1", function (done) {
    var td = testData["paymail-noScheme"];
    testParsing(td.uris[0], td.expected, done);
});
test("paymail-noScheme_#2", function (done) {
    var td = testData["paymail-noScheme"];
    testParsing(td.uris[1], td.expected, done);
});